server:
  port: 8090
spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: animal
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
file:
  upload-dir: ${IMAGES_DIR}
api:
  url: ${API_URL}
