server:
  port: 8090
spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: animal
      authentication-database: admin
  cloud:
    azure:
      storage:
        endpoint: ${AZURE_STORAGE_ENDPOINT}
        connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
