server:
  port: 8222
frontend:
  url: ${FRONTEND_URL:http://localhost:3000}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: animal-service
          uri: lb:http://ANIMAL-SERVICE
          predicates:
            - Path=/api/v1/animals/**
        - id: person-service
          uri: lb:http://PERSON-SERVICE
          predicates:
            - Path=/api/v1/persons/**
        - id: adoption-service
          uri: lb:http://ADOPTION-SERVICE
          predicates:
            - Path=/api/v1/adoption/**
        - id: management-service
          uri: lb:http://MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/managements/**
        - id: event-service
          uri: lb:http://EVENT-SERVICE
          predicates:
            - Path=/api/v1/events/**
  #        Definir demais serviços aqui
